inherit_from: "configs/rgbd/scannetpp/base_config.yaml"

Dataset:
  dataset_path: "/root/code/datasets/hotel"
  scale: True
  scale_width: 640
  scale_height: 480

  Calibration:
    fx: 479.360000
    fy: 480.330000
    cx: 319.685667
    cy: 240.821667
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    distorted: True
    width: 1280
    height: 720
    depth_scale: 5000.0