inherit_from: "/root/code/monogs_ros_ws/src/monogs_ros/monogs_ros/configs/rgbd/tum/base_config.yaml"

Dataset:
  dataset_path: "/root/code/datasets/tum/rgbd_dataset_freiburg1_desk"
  Calibration:
    fx: 520.90862
    fy: 521.007327
    cx: 325.141442
    cy: 249.701764
    k1: 0.2312
    k2: -0.7849
    p1: -0.0033
    p2: -0.0001
    k3: 0.9172
    distorted: True
    width: 640
    height: 480
    depth_scale: 5000.0
